services:
  juno-console:
    image: juno-console
    ports:
      - 5987:5987
      - 5999:5999
    volumes:
      - juno_console_61:/juno/.juno
      - ./target/deploy:/juno/target/deploy/

volumes:
  juno_console_61:
