services:
  juno-console-pocket-ic:
    image: juno-console-pocket-ic
    ports:
      - 5987:5987
      - 5999:5999
    volumes:
      - juno-console-pocket-ic_001:/juno/.juno
      - ./target/deploy:/juno/target/deploy/

volumes:
  juno-console-pocket-ic_001:
