services:
  juno-console:
    image: junobuild/console:latest
    ports:
      - 5987:5987
      - 5999:5999
    volumes:
      - juno_console:/juno/.juno
      - ./target/deploy:/juno/target/deploy/

volumes:
  juno_console:
