/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Account {
	updated_at: bigint;
	credits: Tokens;
	mission_control_id: [] | [Principal];
	provider: [] | [Provider];
	owner: Principal;
	created_at: bigint;
}
export interface Account_1 {
	owner: Principal;
	subaccount: [] | [Uint8Array];
}
export interface AssertMissionControlCenterArgs {
	mission_control_id: Principal;
	user: Principal;
}
export interface AssetEncodingNoContent {
	modified: bigint;
	sha256: Uint8Array;
	total_length: bigint;
}
export interface AssetKey {
	token: [] | [string];
	collection: string;
	owner: Principal;
	name: string;
	description: [] | [string];
	full_path: string;
}
export interface AssetNoContent {
	key: AssetKey;
	updated_at: bigint;
	encodings: Array<[string, AssetEncodingNoContent]>;
	headers: Array<[string, string]>;
	created_at: bigint;
	version: [] | [bigint];
}
export interface AssetsUpgradeOptions {
	clear_existing_assets: [] | [boolean];
}
export interface Authentication {
	delegation: PreparedDelegation;
	account: Account;
}
export type AuthenticationArgs = { OpenId: OpenIdPrepareDelegationArgs };
export interface AuthenticationConfig {
	updated_at: [] | [bigint];
	openid: [] | [AuthenticationConfigOpenId];
	created_at: [] | [bigint];
	version: [] | [bigint];
	internet_identity: [] | [AuthenticationConfigInternetIdentity];
	rules: [] | [AuthenticationRules];
}
export interface AuthenticationConfigInternetIdentity {
	derivation_origin: [] | [string];
	external_alternative_origins: [] | [Array<string>];
}
export interface AuthenticationConfigOpenId {
	observatory_id: [] | [Principal];
	providers: Array<[OpenIdDelegationProvider, OpenIdAuthProviderConfig]>;
}
export type AuthenticationError =
	| {
			PrepareDelegation: PrepareDelegationError;
	  }
	| { RegisterUser: string };
export interface AuthenticationRules {
	allowed_callers: Array<Principal>;
}
export interface CommitBatch {
	batch_id: bigint;
	headers: Array<[string, string]>;
	chunk_ids: Array<bigint>;
}
export interface CommitProposal {
	sha256: Uint8Array;
	proposal_id: bigint;
}
export interface Config {
	authentication: [] | [AuthenticationConfig];
	storage: StorageConfig;
}
export interface ConfigMaxMemorySize {
	stable: [] | [bigint];
	heap: [] | [bigint];
}
export interface Controller {
	updated_at: bigint;
	metadata: Array<[string, string]>;
	kind: [] | [ControllerKind];
	created_at: bigint;
	scope: ControllerScope;
	expires_at: [] | [bigint];
}
export type ControllerKind = { Emulator: null } | { Automation: null };
export type ControllerScope = { Write: null } | { Admin: null } | { Submit: null };
export interface CreateMissionControlArgs {
	subnet_id: [] | [Principal];
}
export interface CreateOrbiterArgs {
	block_index: [] | [bigint];
	subnet_id: [] | [Principal];
	name: [] | [string];
	user: Principal;
}
export interface CreateSatelliteArgs {
	block_index: [] | [bigint];
	subnet_id: [] | [Principal];
	storage: [] | [InitStorageArgs];
	name: [] | [string];
	user: Principal;
}
export interface CustomDomain {
	updated_at: bigint;
	created_at: bigint;
	version: [] | [bigint];
	bn_id: [] | [string];
}
export interface CyclesTokens {
	e12s: bigint;
}
export interface Delegation {
	pubkey: Uint8Array;
	targets: [] | [Array<Principal>];
	expiration: bigint;
}
export interface DeleteControllersArgs {
	controllers: Array<Principal>;
}
export interface DeleteProposalAssets {
	proposal_ids: Array<bigint>;
}
export interface FactoryFee {
	updated_at: bigint;
	fee_cycles: CyclesTokens;
	fee_icp: [] | [Tokens];
}
export interface FeesArgs {
	fee_cycles: CyclesTokens;
	fee_icp: [] | [Tokens];
}
export interface GetCreateCanisterFeeArgs {
	user: Principal;
}
export type GetDelegationArgs = { OpenId: OpenIdGetDelegationArgs };
export type GetDelegationError =
	| { JwtFindProvider: JwtFindProviderError }
	| { GetCachedJwks: null }
	| { NoSuchDelegation: null }
	| { JwtVerify: JwtVerifyError }
	| { GetOrFetchJwks: GetOrRefreshJwksError }
	| { DeriveSeedFailed: string };
export type GetOrRefreshJwksError =
	| { InvalidConfig: string }
	| { MissingKid: null }
	| { BadClaim: string }
	| { KeyNotFoundCooldown: null }
	| { CertificateNotFound: null }
	| { BadSig: string }
	| { MissingLastAttempt: string }
	| { KeyNotFound: null }
	| { FetchFailed: string };
export interface HttpRequest {
	url: string;
	method: string;
	body: Uint8Array;
	headers: Array<[string, string]>;
	certificate_version: [] | [number];
}
export interface HttpResponse {
	body: Uint8Array;
	headers: Array<[string, string]>;
	streaming_strategy: [] | [StreamingStrategy];
	status_code: number;
}
export interface IcpPayment {
	status: PaymentStatus;
	updated_at: bigint;
	block_index_payment: bigint;
	mission_control_id: [] | [Principal];
	created_at: bigint;
	block_index_refunded: [] | [bigint];
}
export interface IcrcPayment {
	status: PaymentStatus;
	updated_at: bigint;
	created_at: bigint;
	block_index_refunded: [] | [bigint];
	purchaser: Account_1;
}
export interface IcrcPaymentKey {
	block_index: bigint;
	ledger_id: Principal;
}
export interface InitAssetKey {
	token: [] | [string];
	collection: string;
	name: string;
	description: [] | [string];
	encoding_type: [] | [string];
	full_path: string;
}
export interface InitStorageArgs {
	system_memory: [] | [InitStorageMemory];
}
export type InitStorageMemory = { Heap: null } | { Stable: null };
export interface InitUploadResult {
	batch_id: bigint;
}
export type JwtFindProviderError =
	| { BadClaim: string }
	| { BadSig: string }
	| { NoMatchingProvider: null };
export type JwtVerifyError =
	| { WrongKeyType: null }
	| { MissingKid: null }
	| { BadClaim: string }
	| { BadSig: string }
	| { NoKeyForKid: null };
export interface ListMatcher {
	key: [] | [string];
	updated_at: [] | [TimestampMatcher];
	description: [] | [string];
	created_at: [] | [TimestampMatcher];
}
export interface ListOrder {
	field: ListOrderField;
	desc: boolean;
}
export type ListOrderField = { UpdatedAt: null } | { Keys: null } | { CreatedAt: null };
export interface ListPaginate {
	start_after: [] | [string];
	limit: [] | [bigint];
}
export interface ListParams {
	order: [] | [ListOrder];
	owner: [] | [Principal];
	matcher: [] | [ListMatcher];
	paginate: [] | [ListPaginate];
}
export interface ListProposalResults {
	matches_length: bigint;
	items: Array<[ProposalKey, Proposal]>;
	items_length: bigint;
}
export interface ListProposalsOrder {
	desc: boolean;
}
export interface ListProposalsPaginate {
	start_after: [] | [bigint];
	limit: [] | [bigint];
}
export interface ListProposalsParams {
	order: [] | [ListProposalsOrder];
	paginate: [] | [ListProposalsPaginate];
}
export interface ListResults {
	matches_pages: [] | [bigint];
	matches_length: bigint;
	items_page: [] | [bigint];
	items: Array<[string, AssetNoContent]>;
	items_length: bigint;
}
export interface ListSegmentsArgs {
	segment_id: [] | [Principal];
	segment_kind: [] | [StorableSegmentKind];
}
export type Memory = { Heap: null } | { Stable: null };
export interface OpenId {
	provider: OpenIdDelegationProvider;
	data: OpenIdData;
}
export interface OpenIdAuthProviderConfig {
	delegation: [] | [OpenIdAuthProviderDelegationConfig];
	client_id: string;
}
export interface OpenIdAuthProviderDelegationConfig {
	targets: [] | [Array<Principal>];
	max_time_to_live: [] | [bigint];
}
export interface OpenIdData {
	name: [] | [string];
	locale: [] | [string];
	family_name: [] | [string];
	email: [] | [string];
	picture: [] | [string];
	given_name: [] | [string];
	preferred_username: [] | [string];
}
export type OpenIdDelegationProvider = { GitHub: null } | { Google: null };
export interface OpenIdGetDelegationArgs {
	jwt: string;
	session_key: Uint8Array;
	salt: Uint8Array;
	expiration: bigint;
}
export interface OpenIdPrepareDelegationArgs {
	jwt: string;
	session_key: Uint8Array;
	salt: Uint8Array;
}
export type PaymentStatus = { Refunded: null } | { Acknowledged: null } | { Completed: null };
export type PrepareDelegationError =
	| {
			JwtFindProvider: JwtFindProviderError;
	  }
	| { GetCachedJwks: null }
	| { JwtVerify: JwtVerifyError }
	| { GetOrFetchJwks: GetOrRefreshJwksError }
	| { DeriveSeedFailed: string };
export interface PreparedDelegation {
	user_key: Uint8Array;
	expiration: bigint;
}
export interface Proposal {
	status: ProposalStatus;
	updated_at: bigint;
	sha256: [] | [Uint8Array];
	executed_at: [] | [bigint];
	owner: Principal;
	created_at: bigint;
	version: [] | [bigint];
	proposal_type: ProposalType;
}
export interface ProposalKey {
	proposal_id: bigint;
}
export type ProposalStatus =
	| { Initialized: null }
	| { Failed: null }
	| { Open: null }
	| { Rejected: null }
	| { Executed: null }
	| { Accepted: null };
export type ProposalType =
	| { AssetsUpgrade: AssetsUpgradeOptions }
	| { SegmentsDeployment: SegmentsDeploymentOptions };
export type Provider = { InternetIdentity: null } | { OpenId: OpenId };
export interface RateConfig {
	max_tokens: bigint;
	time_per_token_ns: bigint;
}
export type Result = { Ok: Authentication } | { Err: AuthenticationError };
export type Result_1 = { Ok: SignedDelegation } | { Err: GetDelegationError };
export interface Segment {
	updated_at: bigint;
	metadata: Array<[string, string]>;
	segment_id: Principal;
	created_at: bigint;
}
export interface SegmentKey {
	user: Principal;
	segment_id: Principal;
	segment_kind: StorableSegmentKind;
}
export type SegmentKind = { Orbiter: null } | { MissionControl: null } | { Satellite: null };
export interface SegmentsDeploymentOptions {
	orbiter: [] | [string];
	mission_control_version: [] | [string];
	satellite_version: [] | [string];
}
export interface SetAuthenticationConfig {
	openid: [] | [AuthenticationConfigOpenId];
	version: [] | [bigint];
	internet_identity: [] | [AuthenticationConfigInternetIdentity];
	rules: [] | [AuthenticationRules];
}
export interface SetController {
	metadata: Array<[string, string]>;
	kind: [] | [ControllerKind];
	scope: ControllerScope;
	expires_at: [] | [bigint];
}
export interface SetControllersArgs {
	controller: SetController;
	controllers: Array<Principal>;
}
export interface SetSegmentMetadataArgs {
	metadata: Array<[string, string]>;
	segment_id: Principal;
	segment_kind: StorableSegmentKind;
}
export interface SetSegmentsArgs {
	metadata: [] | [Array<[string, string]>];
	segment_id: Principal;
	segment_kind: StorableSegmentKind;
}
export interface SetStorageConfig {
	iframe: [] | [StorageConfigIFrame];
	rewrites: Array<[string, string]>;
	headers: Array<[string, Array<[string, string]>]>;
	version: [] | [bigint];
	max_memory_size: [] | [ConfigMaxMemorySize];
	raw_access: [] | [StorageConfigRawAccess];
	redirects: [] | [Array<[string, StorageConfigRedirect]>];
}
export interface SignedDelegation {
	signature: Uint8Array;
	delegation: Delegation;
}
export type StorableSegmentKind = { Orbiter: null } | { Satellite: null };
export interface StorageConfig {
	iframe: [] | [StorageConfigIFrame];
	updated_at: [] | [bigint];
	rewrites: Array<[string, string]>;
	headers: Array<[string, Array<[string, string]>]>;
	created_at: [] | [bigint];
	version: [] | [bigint];
	max_memory_size: [] | [ConfigMaxMemorySize];
	raw_access: [] | [StorageConfigRawAccess];
	redirects: [] | [Array<[string, StorageConfigRedirect]>];
}
export type StorageConfigIFrame = { Deny: null } | { AllowAny: null } | { SameOrigin: null };
export type StorageConfigRawAccess = { Deny: null } | { Allow: null };
export interface StorageConfigRedirect {
	status_code: number;
	location: string;
}
export interface StreamingCallbackHttpResponse {
	token: [] | [StreamingCallbackToken];
	body: Uint8Array;
}
export interface StreamingCallbackToken {
	memory: Memory;
	token: [] | [string];
	sha256: [] | [Uint8Array];
	headers: Array<[string, string]>;
	index: bigint;
	encoding_type: string;
	full_path: string;
}
export type StreamingStrategy = {
	Callback: {
		token: StreamingCallbackToken;
		callback: [Principal, string];
	};
};
export type TimestampMatcher =
	| { Equal: bigint }
	| { Between: [bigint, bigint] }
	| { GreaterThan: bigint }
	| { LessThan: bigint };
export interface Tokens {
	e8s: bigint;
}
export interface UnsetSegmentsArgs {
	segment_id: Principal;
	segment_kind: StorableSegmentKind;
}
export interface UploadChunk {
	content: Uint8Array;
	batch_id: bigint;
	order_id: [] | [bigint];
}
export interface UploadChunkResult {
	chunk_id: bigint;
}
export interface _SERVICE {
	add_credits: ActorMethod<[Principal, Tokens], undefined>;
	add_invitation_code: ActorMethod<[string], undefined>;
	assert_mission_control_center: ActorMethod<[AssertMissionControlCenterArgs], undefined>;
	authenticate: ActorMethod<[AuthenticationArgs], Result>;
	commit_proposal: ActorMethod<[CommitProposal], null>;
	commit_proposal_asset_upload: ActorMethod<[CommitBatch], undefined>;
	commit_proposal_many_assets_upload: ActorMethod<[Array<CommitBatch>], undefined>;
	count_proposals: ActorMethod<[], bigint>;
	create_mission_control: ActorMethod<[CreateMissionControlArgs], Principal>;
	create_orbiter: ActorMethod<[CreateOrbiterArgs], Principal>;
	create_satellite: ActorMethod<[CreateSatelliteArgs], Principal>;
	del_controllers: ActorMethod<[DeleteControllersArgs], undefined>;
	del_custom_domain: ActorMethod<[string], undefined>;
	delete_proposal_assets: ActorMethod<[DeleteProposalAssets], undefined>;
	get_account: ActorMethod<[], [] | [Account]>;
	get_auth_config: ActorMethod<[], [] | [AuthenticationConfig]>;
	get_config: ActorMethod<[], Config>;
	get_create_orbiter_fee: ActorMethod<[GetCreateCanisterFeeArgs], [] | [Tokens]>;
	get_create_satellite_fee: ActorMethod<[GetCreateCanisterFeeArgs], [] | [Tokens]>;
	get_credits: ActorMethod<[], Tokens>;
	get_delegation: ActorMethod<[GetDelegationArgs], Result_1>;
	get_fee: ActorMethod<[SegmentKind], FactoryFee>;
	get_or_init_account: ActorMethod<[], Account>;
	get_proposal: ActorMethod<[bigint], [] | [Proposal]>;
	get_rate_config: ActorMethod<[SegmentKind], RateConfig>;
	get_storage_config: ActorMethod<[], StorageConfig>;
	http_request: ActorMethod<[HttpRequest], HttpResponse>;
	http_request_streaming_callback: ActorMethod<
		[StreamingCallbackToken],
		StreamingCallbackHttpResponse
	>;
	init_proposal: ActorMethod<[ProposalType], [bigint, Proposal]>;
	init_proposal_asset_upload: ActorMethod<[InitAssetKey, bigint], InitUploadResult>;
	init_proposal_many_assets_upload: ActorMethod<
		[Array<InitAssetKey>, bigint],
		Array<[string, InitUploadResult]>
	>;
	list_accounts: ActorMethod<[], Array<[Principal, Account]>>;
	list_assets: ActorMethod<[string, ListParams], ListResults>;
	list_controllers: ActorMethod<[], Array<[Principal, Controller]>>;
	list_custom_domains: ActorMethod<[], Array<[string, CustomDomain]>>;
	list_icp_payments: ActorMethod<[], Array<[bigint, IcpPayment]>>;
	list_icrc_payments: ActorMethod<[], Array<[IcrcPaymentKey, IcrcPayment]>>;
	list_proposals: ActorMethod<[ListProposalsParams], ListProposalResults>;
	list_segments: ActorMethod<[ListSegmentsArgs], Array<[SegmentKey, Segment]>>;
	reject_proposal: ActorMethod<[CommitProposal], null>;
	set_auth_config: ActorMethod<[SetAuthenticationConfig], AuthenticationConfig>;
	set_controllers: ActorMethod<[SetControllersArgs], undefined>;
	set_custom_domain: ActorMethod<[string, [] | [string]], undefined>;
	set_fee: ActorMethod<[SegmentKind, FeesArgs], undefined>;
	set_many_segments: ActorMethod<[Array<SetSegmentsArgs>], Array<Segment>>;
	set_rate_config: ActorMethod<[SegmentKind, RateConfig], undefined>;
	set_segment: ActorMethod<[SetSegmentsArgs], Segment>;
	set_segment_metadata: ActorMethod<[SetSegmentMetadataArgs], Segment>;
	set_storage_config: ActorMethod<[SetStorageConfig], StorageConfig>;
	submit_proposal: ActorMethod<[bigint], [bigint, Proposal]>;
	unset_many_segments: ActorMethod<[Array<UnsetSegmentsArgs>], undefined>;
	unset_segment: ActorMethod<[UnsetSegmentsArgs], undefined>;
	upload_proposal_asset_chunk: ActorMethod<[UploadChunk], UploadChunkResult>;
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
