name: Run emulator

description: Start and config the emulator

runs:
  using: composite
  steps:
    - name: Run emulator
      shell: bash
      run: |
        set -e
        ./scripts/emulator.sh --headless &
        npm run emulator:wait

    - name: Identity Console controller locally
      shell: bash
      run: |
        set -e
        node ./scripts/console.controller.mjs

    # We have copied the WASMs into target/deploy
    # Therefore, the latest Satellite, Mission Control and Orbiter
    # were already uploaded to the Console at boot time
    - name: Upgrade the Console
      shell: bash
      run: |
        set -e
        node ./scripts/console.upgrade.mjs --headless
