pub const STRING_MAX_LENGTH: usize = 1024;
pub const METADATA_MAX_ELEMENTS: usize = 10;
pub const KEY_MAX_LENGTH: usize = 36; // UUID length

pub const SERIALIZED_PRINCIPAL_LENGTH: usize = 30;
pub const SERIALIZED_STRING_LENGTH: usize = STRING_MAX_LENGTH + 1;
pub const SERIALIZED_KEY_LENGTH: usize = KEY_MAX_LENGTH + 1;
pub const SERIALIZED_METADATA_LENGTH: usize =
    METADATA_MAX_ELEMENTS * (SERIALIZED_STRING_LENGTH * 2);
