#!/usr/bin/env bash

set -euo pipefail

function pre_build_canister() {
    if [[ $# -eq 0 ]]; then
        echo "WARNING: No arguments provided. Skipping pre-building canister."
        return 0
    fi

    while [[ $# -gt 0 ]]
    do
        case "$1" in
            --test_sputnik)
                build_test_sputnik_fixtures
                export_test_sputnik_fixtures
                ;;
        esac
        shift
    done
}

function export_test_sputnik_fixtures() {
  export DEV_SCRIPT_PATH="$PWD/target/fixtures/index.mjs"

  echo "[test_sputnik] DEV_SCRIPT_PATH set to $DEV_SCRIPT_PATH"
  echo
}

function build_test_sputnik_fixtures() {
  DIST="$PWD/target/fixtures"
  ENTRY="$PWD/src/tests/fixtures/test_sputnik/resources/index.ts"
  OUTFILE="$DIST/index.mjs"

  if [ -d "$DIST" ]; then
    rm -rf "$DIST"
  fi

  mkdir -p "$DIST"

  npx esbuild "$ENTRY" \
    --outfile="$OUTFILE" \
    --bundle \
    --minify \
    --tree-shaking=true \
    --format=esm \
    --platform=browser \
    --define:self=globalThis \
    --supported:top-level-await=false \
    --supported:inline-script=false \
    --supported:dynamic-import=false

  echo
  echo "[test_sputnik] $DIST/index.mjs generated"
  echo
}