name: Download WASM Artifacts

description: Downloads the WASM build artifacts

runs:
  using: "composite"
  steps:
    - name: Download satellite.wasm.gz
      uses: actions/download-artifact@v4
      with:
        name: satellite.wasm.gz
        path: .

    - name: Download orbiter.wasm.gz
      uses: actions/download-artifact@v4
      with:
        name: orbiter.wasm.gz
        path: .

    - name: Download sputnik.wasm.gz
      uses: actions/download-artifact@v4
      with:
        name: sputnik.wasm.gz
        path: .

    - name: Download console.wasm.gz
      uses: actions/download-artifact@v4
      with:
        name: console.wasm.gz
        path: .

    - name: Download observatory.wasm.gz
      uses: actions/download-artifact@v4
      with:
        name: observatory.wasm.gz
        path: .

    - name: Download mission_control.wasm.gz
      uses: actions/download-artifact@v4
      with:
        name: mission_control.wasm.gz
        path: .

    - name: Download test_satellite.wasm.gz
      uses: actions/download-artifact@v4
      with:
        name: test_satellite.wasm.gz
        path: .

    - name: Download test_sputnik.wasm.gz
      uses: actions/download-artifact@v4
      with:
        name: test_sputnik.wasm.gz
        path: .
