#![allow(clippy::needless_lifetimes)]
#![deny(clippy::disallowed_methods)]

mod errors;
mod hooks;
mod js;
mod polyfill;
mod state;

// Developer's custom serverless functions endpoints. Generated by build.rs.
mod generated;

use junobuild_satellite::include_satellite;

include_satellite!();
