const MINUTE_NANOSECONDS = 60n * 1_000_000_000n;
const HOUR_NANOSECONDS = 60n * MINUTE_NANOSECONDS;

export const TWO_MINUTES_NS = 2n * MINUTE_NANOSECONDS;
export const FIVE_MINUTES_NS = 5n * MINUTE_NANOSECONDS;
export const TEN_MINUTES_NS = 10n * MINUTE_NANOSECONDS;
export const FIFTEEN_MINUTES_NS = 15n * MINUTE_NANOSECONDS;
export const THIRTY_MINUTES_NS = 30n * MINUTE_NANOSECONDS;
export const FORTY_FIVE_MINUTES_NS = 45n * MINUTE_NANOSECONDS;

export const AUTOMATION_DEFAULT_MAX_SESSION_TIME_TO_LIVE = TEN_MINUTES_NS;
