name: Frontend Checks

on:
  pull_request:
    paths:
      - 'src/frontend/**'
      - 'package-lock.json'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: Lint
        run: npm run lint

  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: Lint
        run: npm run check

  check-unused-svelte:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: Lint
        run: npm run check:unused:svelte

  may-merge:
    needs: ['check', 'lint', 'check-unused-svelte']
    runs-on: ubuntu-latest
    steps:
      - name: Cleared for merging
        run: echo OK
