name: Frontend Reproducibility

on:
  workflow_dispatch:

jobs:
  frontend-reproducibility:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Run reproducibility test
        run: bash .github/scripts/test-frontend-reproducibility
        shell: bash

      - name: Check script exit status
        run: |
          exit_code=$?
          echo "Script exited with code $exit_code"
          if [ $exit_code -ne 0 ]; then
            echo "Difference detected in build files"
            exit 1
          else
            echo "No difference found"
          fi
