name: 'PR Checks'

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - labeled
  merge_group:

permissions: {}

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    env:
      TITLE: ${{ github.event.pull_request.title }}
    steps:
      - name: 'Check PR Title'
        run: |
          if [[ "$TITLE" =~ ^(feat|fix|chore|build|ci|docs|style|refactor|perf|test)(\([-a-zA-Z0-9,]+\))\!?\: ]]; then
              echo "PR Title passes"
          else
              echo "PR Title does not match conventions:"
              echo "   verb(scope): description"
              echo "or for a breaking change:"
              echo "   verb(scope)!: description"
              echo "For scope, please use the affected module name(s), crate(s), 'frontend' or 'ci' for infrastructure changes."
              exit 1
          fi

  may-merge:
    needs: [ 'check-pr-title' ]
    runs-on: ubuntu-latest
    steps:
      - name: Cleared for merging
        run: echo OK